---
# Ansible Galaxy Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Windows automation and management
  - name: ansible.windows
    version: ">=2.0.0"
    
  # Azure cloud automation
  - name: azure.azcollection
    version: ">=1.19.0"
    
  # Community Windows modules
  - name: community.windows
    version: ">=2.0.0"
    
  # General utilities
  - name: ansible.posix
    version: ">=1.5.0"
    
  # Crypto and certificates
  - name: community.crypto
    version: ">=2.0.0"